### PR TITLE
[#2] symlink driver handling

### PR DESCRIPTION
**Pull request by kreuzberger**
I have merged my changes into the collections and drivers. I added a first test framework by adapting the structure and tooling from sphinxcontrib-needs. ATTENTION: This is "borg" style, i do not realy in deep know that i do here, its more adaption.
The tests for string and symlink worked for me in this environment:
* Ubuntu 20.04
* Python 3.8 (from System)
* nox test against sphinx versions >= 4.0

I fixed also documentation errors and other stuff. Feel free to correct.

### CODE REVIEW

**Comment by kreuzberger** [comment]
I think it would now be easy to adapt the repository for automatic tests with github actions.

**Comment by danwos** [comment]
Ohh nice, thanks for this helpful PR :+1: 

I will need some time to get through it and I hope to find some time today or on Monday.

**Comment by kreuzberger** [comment]
Last commit was done with newest Ubuntu 22.04 and Python 3.10.4 from system.

**Comment by danwos** [comment]
Just time and, shame on me, I forgot to review it.
I will do it shortly.

(Freel free to send another reminder, if not done in -12 days)

**Review by danwos — APPROVED** [review]
Looks good. :+1:
And a huge "Thank you" for all the effort you spend on this.

**Pull request merged**
